sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

before_cache:
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
    - rm -r -f $HOME/.ivy2/local/

language: scala
script:
  - sbt formatAll
  - if [[ -n $(git status -s) ]]; then git status && echo 'You need to format your code!' && exit 1; fi
  - ./.bintray_setup_credentials.sh
  - sbt clean "set coverageEnabled in monitoring := true" test monitoring/coverageReport monitoring/codacyCoverage || exit 1
  - sbt scripted || exit 1

jdk:
  - oraclejdk8

notifications:
  email:
    - lukasz.stefaniak@blstream.com

after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -n "$TRAVIS_TAG" -o "$TRAVIS_BRANCH" == "master" ]; then sbt publish; fi
  - bash <(curl -s https://codecov.io/bash)
